use_lockfile = false

[project]
name = "scicalc"
r_version = "4.5"

repositories = [
	{ alias = "ppm", url = "https://packagemanager.posit.co/cran/latest" },
]

dependencies = [
	{ name = "scicalc", path = ".", dependencies_only = false, install_suggestions = true },
]
