use_lockfile = false

[project]
name = "scicalc"
r_version = "4.5"

repositories = [
	{ alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2026-01-29/" },
]

dependencies = [
	"devtools",
	{ name = "covr", install_suggestions = true },
	{ name = "scicalc", path = ".", dependencies_only = false, install_suggestions = true },
	{ name = "starlightr", git = "https://github.com/a2-ai/starlightr", branch = "main" },
    "lobstr",
]
